import gameImg from "~/assets/images/eldenRing.png";
import { Game } from "./definitions";

export const DUMMY_GAMES: Game[] = [
  {
    id: 1,
    title: "Elden Ring",
    image: gameImg,
    developer: "DEFAULT",
    price: 888,
    rating: 3.6,
  },
  {
    id: 1,
    title: "Elden Ring",
    image: gameImg,
    developer: "DEFAULT",
    price: 888,
    rating: 3.6,
  },
  {
    id: 1,
    title: "Elden Ring",
    image: gameImg,
    developer: "DEFAULT",
    price: 888,
    rating: 3.6,
  },
  {
    id: 1,
    title: "Elden Ring",
    image: gameImg,
    developer: "DEFAULT",
    price: 888,
    rating: 3.6,
  },
  {
    id: 1,
    title: "Elden Ring",
    image: gameImg,
    developer: "DEFAULT",
    price: 888,
    rating: 3.6,
  },
  {
    id: 1,
    title: "Elden Ring",
    image: gameImg,
    developer: "DEFAULT",
    price: 888,
    rating: 3.6,
  },
  {
    id: 1,
    title: "Elden Ring",
    image: gameImg,
    developer: "DEFAULT",
    price: 888,
    rating: 3.6,
  },
  {
    id: 1,
    title: "Elden Ring",
    image: gameImg,
    developer: "DEFAULT",
    price: 888,
    rating: 3.6,
  },
  {
    id: 1,
    title: "Elden Ring",
    image: gameImg,
    developer: "DEFAULT",
    price: 888,
    rating: 3.6,
  },
  {
    id: 1,
    title: "Elden Ring",
    image: gameImg,
    developer: "DEFAULT",
    price: 888,
    rating: 3.6,
  },
  {
    id: 1,
    title: "Elden Ring",
    image: gameImg,
    developer: "DEFAULT",
    price: 888,
    rating: 3.6,
  },
];
